// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databaseconnector.proxies;

public class objDadosTelemetria extends databaseconnector.proxies.Statement
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseConnector.objDadosTelemetria";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		idTelemetria("idTelemetria"),
		idSecador("idSecador"),
		secador("secador"),
		idTipoTelemetria("idTipoTelemetria"),
		tipoTelemetria("tipoTelemetria"),
		dataHoraTelemetria("dataHoraTelemetria"),
		valor("valor"),
		umidadeMinimaAceitavel("umidadeMinimaAceitavel"),
		temperaturaMaximaAceitavel("temperaturaMaximaAceitavel"),
		Content("Content"),
		Statement_Parameter("DatabaseConnector.Statement_Parameter");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public objDadosTelemetria(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected objDadosTelemetria(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject objDadosTelemetriaMendixObject)
	{
		super(context, objDadosTelemetriaMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, objDadosTelemetriaMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'objDadosTelemetria.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databaseconnector.proxies.objDadosTelemetria initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databaseconnector.proxies.objDadosTelemetria.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static databaseconnector.proxies.objDadosTelemetria initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databaseconnector.proxies.objDadosTelemetria(context, mendixObject);
	}

	public static databaseconnector.proxies.objDadosTelemetria load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databaseconnector.proxies.objDadosTelemetria.initialize(context, mendixObject);
	}

	/**
	 * @return value of idTelemetria
	 */
	public final java.lang.Integer getidTelemetria()
	{
		return getidTelemetria(getContext());
	}

	/**
	 * @param context
	 * @return value of idTelemetria
	 */
	public final java.lang.Integer getidTelemetria(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.idTelemetria.toString());
	}

	/**
	 * Set value of idTelemetria
	 * @param idtelemetria
	 */
	public final void setidTelemetria(java.lang.Integer idtelemetria)
	{
		setidTelemetria(getContext(), idtelemetria);
	}

	/**
	 * Set value of idTelemetria
	 * @param context
	 * @param idtelemetria
	 */
	public final void setidTelemetria(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer idtelemetria)
	{
		getMendixObject().setValue(context, MemberNames.idTelemetria.toString(), idtelemetria);
	}

	/**
	 * @return value of idSecador
	 */
	public final java.lang.Integer getidSecador()
	{
		return getidSecador(getContext());
	}

	/**
	 * @param context
	 * @return value of idSecador
	 */
	public final java.lang.Integer getidSecador(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.idSecador.toString());
	}

	/**
	 * Set value of idSecador
	 * @param idsecador
	 */
	public final void setidSecador(java.lang.Integer idsecador)
	{
		setidSecador(getContext(), idsecador);
	}

	/**
	 * Set value of idSecador
	 * @param context
	 * @param idsecador
	 */
	public final void setidSecador(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer idsecador)
	{
		getMendixObject().setValue(context, MemberNames.idSecador.toString(), idsecador);
	}

	/**
	 * @return value of secador
	 */
	public final java.lang.String getsecador()
	{
		return getsecador(getContext());
	}

	/**
	 * @param context
	 * @return value of secador
	 */
	public final java.lang.String getsecador(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.secador.toString());
	}

	/**
	 * Set value of secador
	 * @param secador
	 */
	public final void setsecador(java.lang.String secador)
	{
		setsecador(getContext(), secador);
	}

	/**
	 * Set value of secador
	 * @param context
	 * @param secador
	 */
	public final void setsecador(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secador)
	{
		getMendixObject().setValue(context, MemberNames.secador.toString(), secador);
	}

	/**
	 * @return value of idTipoTelemetria
	 */
	public final java.lang.Integer getidTipoTelemetria()
	{
		return getidTipoTelemetria(getContext());
	}

	/**
	 * @param context
	 * @return value of idTipoTelemetria
	 */
	public final java.lang.Integer getidTipoTelemetria(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.idTipoTelemetria.toString());
	}

	/**
	 * Set value of idTipoTelemetria
	 * @param idtipotelemetria
	 */
	public final void setidTipoTelemetria(java.lang.Integer idtipotelemetria)
	{
		setidTipoTelemetria(getContext(), idtipotelemetria);
	}

	/**
	 * Set value of idTipoTelemetria
	 * @param context
	 * @param idtipotelemetria
	 */
	public final void setidTipoTelemetria(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer idtipotelemetria)
	{
		getMendixObject().setValue(context, MemberNames.idTipoTelemetria.toString(), idtipotelemetria);
	}

	/**
	 * @return value of tipoTelemetria
	 */
	public final java.lang.String gettipoTelemetria()
	{
		return gettipoTelemetria(getContext());
	}

	/**
	 * @param context
	 * @return value of tipoTelemetria
	 */
	public final java.lang.String gettipoTelemetria(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.tipoTelemetria.toString());
	}

	/**
	 * Set value of tipoTelemetria
	 * @param tipotelemetria
	 */
	public final void settipoTelemetria(java.lang.String tipotelemetria)
	{
		settipoTelemetria(getContext(), tipotelemetria);
	}

	/**
	 * Set value of tipoTelemetria
	 * @param context
	 * @param tipotelemetria
	 */
	public final void settipoTelemetria(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tipotelemetria)
	{
		getMendixObject().setValue(context, MemberNames.tipoTelemetria.toString(), tipotelemetria);
	}

	/**
	 * @return value of dataHoraTelemetria
	 */
	public final java.util.Date getdataHoraTelemetria()
	{
		return getdataHoraTelemetria(getContext());
	}

	/**
	 * @param context
	 * @return value of dataHoraTelemetria
	 */
	public final java.util.Date getdataHoraTelemetria(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.dataHoraTelemetria.toString());
	}

	/**
	 * Set value of dataHoraTelemetria
	 * @param datahoratelemetria
	 */
	public final void setdataHoraTelemetria(java.util.Date datahoratelemetria)
	{
		setdataHoraTelemetria(getContext(), datahoratelemetria);
	}

	/**
	 * Set value of dataHoraTelemetria
	 * @param context
	 * @param datahoratelemetria
	 */
	public final void setdataHoraTelemetria(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datahoratelemetria)
	{
		getMendixObject().setValue(context, MemberNames.dataHoraTelemetria.toString(), datahoratelemetria);
	}

	/**
	 * @return value of valor
	 */
	public final java.math.BigDecimal getvalor()
	{
		return getvalor(getContext());
	}

	/**
	 * @param context
	 * @return value of valor
	 */
	public final java.math.BigDecimal getvalor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.valor.toString());
	}

	/**
	 * Set value of valor
	 * @param valor
	 */
	public final void setvalor(java.math.BigDecimal valor)
	{
		setvalor(getContext(), valor);
	}

	/**
	 * Set value of valor
	 * @param context
	 * @param valor
	 */
	public final void setvalor(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal valor)
	{
		getMendixObject().setValue(context, MemberNames.valor.toString(), valor);
	}

	/**
	 * @return value of umidadeMinimaAceitavel
	 */
	public final java.lang.Integer getumidadeMinimaAceitavel()
	{
		return getumidadeMinimaAceitavel(getContext());
	}

	/**
	 * @param context
	 * @return value of umidadeMinimaAceitavel
	 */
	public final java.lang.Integer getumidadeMinimaAceitavel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.umidadeMinimaAceitavel.toString());
	}

	/**
	 * Set value of umidadeMinimaAceitavel
	 * @param umidademinimaaceitavel
	 */
	public final void setumidadeMinimaAceitavel(java.lang.Integer umidademinimaaceitavel)
	{
		setumidadeMinimaAceitavel(getContext(), umidademinimaaceitavel);
	}

	/**
	 * Set value of umidadeMinimaAceitavel
	 * @param context
	 * @param umidademinimaaceitavel
	 */
	public final void setumidadeMinimaAceitavel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer umidademinimaaceitavel)
	{
		getMendixObject().setValue(context, MemberNames.umidadeMinimaAceitavel.toString(), umidademinimaaceitavel);
	}

	/**
	 * @return value of temperaturaMaximaAceitavel
	 */
	public final java.lang.Integer gettemperaturaMaximaAceitavel()
	{
		return gettemperaturaMaximaAceitavel(getContext());
	}

	/**
	 * @param context
	 * @return value of temperaturaMaximaAceitavel
	 */
	public final java.lang.Integer gettemperaturaMaximaAceitavel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.temperaturaMaximaAceitavel.toString());
	}

	/**
	 * Set value of temperaturaMaximaAceitavel
	 * @param temperaturamaximaaceitavel
	 */
	public final void settemperaturaMaximaAceitavel(java.lang.Integer temperaturamaximaaceitavel)
	{
		settemperaturaMaximaAceitavel(getContext(), temperaturamaximaaceitavel);
	}

	/**
	 * Set value of temperaturaMaximaAceitavel
	 * @param context
	 * @param temperaturamaximaaceitavel
	 */
	public final void settemperaturaMaximaAceitavel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer temperaturamaximaaceitavel)
	{
		getMendixObject().setValue(context, MemberNames.temperaturaMaximaAceitavel.toString(), temperaturamaximaaceitavel);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databaseconnector.proxies.objDadosTelemetria that = (databaseconnector.proxies.objDadosTelemetria) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
