// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databaseconnector.proxies;

public class objTemperatura extends databaseconnector.proxies.Statement
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseConnector.objTemperatura";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		dataLog("dataLog"),
		secador("secador"),
		menorTemperatura("menorTemperatura"),
		maiorTemperatura("maiorTemperatura"),
		temperaturaMedia("temperaturaMedia"),
		Content("Content"),
		Statement_Parameter("DatabaseConnector.Statement_Parameter");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public objTemperatura(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected objTemperatura(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject objTemperaturaMendixObject)
	{
		super(context, objTemperaturaMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, objTemperaturaMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'objTemperatura.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databaseconnector.proxies.objTemperatura initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databaseconnector.proxies.objTemperatura.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static databaseconnector.proxies.objTemperatura initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databaseconnector.proxies.objTemperatura(context, mendixObject);
	}

	public static databaseconnector.proxies.objTemperatura load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databaseconnector.proxies.objTemperatura.initialize(context, mendixObject);
	}

	/**
	 * @return value of dataLog
	 */
	public final java.util.Date getdataLog()
	{
		return getdataLog(getContext());
	}

	/**
	 * @param context
	 * @return value of dataLog
	 */
	public final java.util.Date getdataLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.dataLog.toString());
	}

	/**
	 * Set value of dataLog
	 * @param datalog
	 */
	public final void setdataLog(java.util.Date datalog)
	{
		setdataLog(getContext(), datalog);
	}

	/**
	 * Set value of dataLog
	 * @param context
	 * @param datalog
	 */
	public final void setdataLog(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datalog)
	{
		getMendixObject().setValue(context, MemberNames.dataLog.toString(), datalog);
	}

	/**
	 * @return value of secador
	 */
	public final java.lang.String getsecador()
	{
		return getsecador(getContext());
	}

	/**
	 * @param context
	 * @return value of secador
	 */
	public final java.lang.String getsecador(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.secador.toString());
	}

	/**
	 * Set value of secador
	 * @param secador
	 */
	public final void setsecador(java.lang.String secador)
	{
		setsecador(getContext(), secador);
	}

	/**
	 * Set value of secador
	 * @param context
	 * @param secador
	 */
	public final void setsecador(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secador)
	{
		getMendixObject().setValue(context, MemberNames.secador.toString(), secador);
	}

	/**
	 * @return value of menorTemperatura
	 */
	public final java.lang.String getmenorTemperatura()
	{
		return getmenorTemperatura(getContext());
	}

	/**
	 * @param context
	 * @return value of menorTemperatura
	 */
	public final java.lang.String getmenorTemperatura(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.menorTemperatura.toString());
	}

	/**
	 * Set value of menorTemperatura
	 * @param menortemperatura
	 */
	public final void setmenorTemperatura(java.lang.String menortemperatura)
	{
		setmenorTemperatura(getContext(), menortemperatura);
	}

	/**
	 * Set value of menorTemperatura
	 * @param context
	 * @param menortemperatura
	 */
	public final void setmenorTemperatura(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String menortemperatura)
	{
		getMendixObject().setValue(context, MemberNames.menorTemperatura.toString(), menortemperatura);
	}

	/**
	 * @return value of maiorTemperatura
	 */
	public final java.lang.String getmaiorTemperatura()
	{
		return getmaiorTemperatura(getContext());
	}

	/**
	 * @param context
	 * @return value of maiorTemperatura
	 */
	public final java.lang.String getmaiorTemperatura(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.maiorTemperatura.toString());
	}

	/**
	 * Set value of maiorTemperatura
	 * @param maiortemperatura
	 */
	public final void setmaiorTemperatura(java.lang.String maiortemperatura)
	{
		setmaiorTemperatura(getContext(), maiortemperatura);
	}

	/**
	 * Set value of maiorTemperatura
	 * @param context
	 * @param maiortemperatura
	 */
	public final void setmaiorTemperatura(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String maiortemperatura)
	{
		getMendixObject().setValue(context, MemberNames.maiorTemperatura.toString(), maiortemperatura);
	}

	/**
	 * @return value of temperaturaMedia
	 */
	public final java.lang.String gettemperaturaMedia()
	{
		return gettemperaturaMedia(getContext());
	}

	/**
	 * @param context
	 * @return value of temperaturaMedia
	 */
	public final java.lang.String gettemperaturaMedia(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.temperaturaMedia.toString());
	}

	/**
	 * Set value of temperaturaMedia
	 * @param temperaturamedia
	 */
	public final void settemperaturaMedia(java.lang.String temperaturamedia)
	{
		settemperaturaMedia(getContext(), temperaturamedia);
	}

	/**
	 * Set value of temperaturaMedia
	 * @param context
	 * @param temperaturamedia
	 */
	public final void settemperaturaMedia(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String temperaturamedia)
	{
		getMendixObject().setValue(context, MemberNames.temperaturaMedia.toString(), temperaturamedia);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databaseconnector.proxies.objTemperatura that = (databaseconnector.proxies.objTemperatura) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
