// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databaseconnector.proxies;

public class objUmidade extends databaseconnector.proxies.Statement
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseConnector.objUmidade";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		dataLog("dataLog"),
		secador("secador"),
		maiorUmidade("maiorUmidade"),
		umidadeMedia("umidadeMedia"),
		menorUmidade("menorUmidade"),
		Content("Content"),
		Statement_Parameter("DatabaseConnector.Statement_Parameter");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public objUmidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected objUmidade(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject objUmidadeMendixObject)
	{
		super(context, objUmidadeMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, objUmidadeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'objUmidade.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databaseconnector.proxies.objUmidade initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databaseconnector.proxies.objUmidade.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static databaseconnector.proxies.objUmidade initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databaseconnector.proxies.objUmidade(context, mendixObject);
	}

	public static databaseconnector.proxies.objUmidade load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databaseconnector.proxies.objUmidade.initialize(context, mendixObject);
	}

	/**
	 * @return value of dataLog
	 */
	public final java.util.Date getdataLog()
	{
		return getdataLog(getContext());
	}

	/**
	 * @param context
	 * @return value of dataLog
	 */
	public final java.util.Date getdataLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.dataLog.toString());
	}

	/**
	 * Set value of dataLog
	 * @param datalog
	 */
	public final void setdataLog(java.util.Date datalog)
	{
		setdataLog(getContext(), datalog);
	}

	/**
	 * Set value of dataLog
	 * @param context
	 * @param datalog
	 */
	public final void setdataLog(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datalog)
	{
		getMendixObject().setValue(context, MemberNames.dataLog.toString(), datalog);
	}

	/**
	 * @return value of secador
	 */
	public final java.lang.String getsecador()
	{
		return getsecador(getContext());
	}

	/**
	 * @param context
	 * @return value of secador
	 */
	public final java.lang.String getsecador(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.secador.toString());
	}

	/**
	 * Set value of secador
	 * @param secador
	 */
	public final void setsecador(java.lang.String secador)
	{
		setsecador(getContext(), secador);
	}

	/**
	 * Set value of secador
	 * @param context
	 * @param secador
	 */
	public final void setsecador(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secador)
	{
		getMendixObject().setValue(context, MemberNames.secador.toString(), secador);
	}

	/**
	 * @return value of maiorUmidade
	 */
	public final java.lang.String getmaiorUmidade()
	{
		return getmaiorUmidade(getContext());
	}

	/**
	 * @param context
	 * @return value of maiorUmidade
	 */
	public final java.lang.String getmaiorUmidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.maiorUmidade.toString());
	}

	/**
	 * Set value of maiorUmidade
	 * @param maiorumidade
	 */
	public final void setmaiorUmidade(java.lang.String maiorumidade)
	{
		setmaiorUmidade(getContext(), maiorumidade);
	}

	/**
	 * Set value of maiorUmidade
	 * @param context
	 * @param maiorumidade
	 */
	public final void setmaiorUmidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String maiorumidade)
	{
		getMendixObject().setValue(context, MemberNames.maiorUmidade.toString(), maiorumidade);
	}

	/**
	 * @return value of umidadeMedia
	 */
	public final java.lang.String getumidadeMedia()
	{
		return getumidadeMedia(getContext());
	}

	/**
	 * @param context
	 * @return value of umidadeMedia
	 */
	public final java.lang.String getumidadeMedia(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.umidadeMedia.toString());
	}

	/**
	 * Set value of umidadeMedia
	 * @param umidademedia
	 */
	public final void setumidadeMedia(java.lang.String umidademedia)
	{
		setumidadeMedia(getContext(), umidademedia);
	}

	/**
	 * Set value of umidadeMedia
	 * @param context
	 * @param umidademedia
	 */
	public final void setumidadeMedia(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String umidademedia)
	{
		getMendixObject().setValue(context, MemberNames.umidadeMedia.toString(), umidademedia);
	}

	/**
	 * @return value of menorUmidade
	 */
	public final java.lang.String getmenorUmidade()
	{
		return getmenorUmidade(getContext());
	}

	/**
	 * @param context
	 * @return value of menorUmidade
	 */
	public final java.lang.String getmenorUmidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.menorUmidade.toString());
	}

	/**
	 * Set value of menorUmidade
	 * @param menorumidade
	 */
	public final void setmenorUmidade(java.lang.String menorumidade)
	{
		setmenorUmidade(getContext(), menorumidade);
	}

	/**
	 * Set value of menorUmidade
	 * @param context
	 * @param menorumidade
	 */
	public final void setmenorUmidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String menorumidade)
	{
		getMendixObject().setValue(context, MemberNames.menorUmidade.toString(), menorumidade);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databaseconnector.proxies.objUmidade that = (databaseconnector.proxies.objUmidade) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
