// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import UrlParse from "url-parse";

// BEGIN EXTRA CODE
async function getQuerParameter(url, param){
	const urlObject = new UrlParse(url,true);		
	return urlObject.query[param] != undefined ? urlObject.query[param] : "";
}
// END EXTRA CODE

/**
 * @param {string} uRL
 * @param {string} parameter
 * @returns {Promise.<string>}
 */
export async function URLQueryParameter(uRL, parameter) {
	// BEGIN USER CODE
	return getQuerParameter(uRL, parameter);
	// END USER CODE
}
