// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package siemensinsightshubsinglesignon.actions;

import java.util.Optional;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import siemensinsightshubsinglesignon.CredentialsHandler;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class PutAccessToken extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __ACResponse;
	private siemensinsightshubsinglesignon.proxies.CredentialsResponse ACResponse;

	public PutAccessToken(IContext context, IMendixObject ACResponse)
	{
		super(context);
		this.__ACResponse = ACResponse;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.ACResponse = this.__ACResponse == null ? null : siemensinsightshubsinglesignon.proxies.CredentialsResponse.initialize(getContext(), __ACResponse);

		// BEGIN USER CODE
		Optional<IMxRuntimeRequest> mayBeIMxRuntimeRequest = context().getRuntimeRequest();
		if (mayBeIMxRuntimeRequest.isPresent()){
			CredentialsHandler.storeCredentialsResponsInSession(mayBeIMxRuntimeRequest.get(), this.ACResponse);			
			return true;
		}
		return false;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PutAccessToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
