// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubsinglesignon.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the SiemensInsightsHubSingleSignOn module

	/**
	* Sample forward exception configuration:
	* 
	* [
	*   {    
	*     "host": "http://localhost:4001",
	*     "pattern": "^/api/oee/v3/assets/[a-f0-9]{32}/timeModelCategoryDistribution$",
	*     "resourcePattern": "^/api/oee/v3",
	*     "resourcePatternReplacement": "/protected"
	*   }
	* ]
	*/
	public static java.lang.String getApiReverseProxyConfig()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.ApiReverseProxyConfig");
	}

	/**
	* Add your apple-app-site-association file here.
	*/
	public static java.lang.String getAppleAppSiteAssociation()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.AppleAppSiteAssociation");
	}

	public static boolean getAskForCredentialsOnStartup()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.AskForCredentialsOnStartup");
	}

	/**
	* Generate your digital asset links file with Android Studio and paste the content here.
	* 
	* Hint: remove /r/n from the json file
	*/
	public static java.lang.String getAssetLinks()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.AssetLinks");
	}

	/**
	* The clientId of your mobile app from the Developer Cockpit application registration
	*/
	public static java.lang.String getClientId()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.ClientId");
	}

	/**
	* The clientSecret of your mobile app from the Developer Cockpit application registration
	*/
	public static java.lang.String getClientSecret()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.ClientSecret");
	}

	/**
	* Name of the application used in the Developer Cockpit.
	* 
	* This is used for JWT validation process and is mapped to the "aud" claim.
	*/
	public static java.lang.String getCockpitApplicationName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.CockpitApplicationName");
	}

	/**
	* Used to get application credentials, must be identical to the version in the Developer Cockpit.
	*/
	public static java.lang.String getCockpitApplicationVersion()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.CockpitApplicationVersion");
	}

	/**
	* Required to use the Siemens Insights Hub Web Component Widgets
	*/
	public static boolean getEnableLocalApiReverseProxy()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.EnableLocalApiReverseProxy");
	}

	/**
	* The Gateway URL
	*/
	public static java.lang.String getGatewayURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.GatewayURL");
	}

	/**
	* Name of Tenant where application is hosted.
	* Name is used during retrieval of application credentials.
	*/
	public static java.lang.String getHostTenant()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.HostTenant");
	}

	/**
	* InsigtsHubSingleSignOn
	*/
	public static java.lang.String getModuleName()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.ModuleName");
	}

	/**
	* Endpoint where to fetcht the public keys for token validation.
	*/
	public static java.lang.String getPublicKeyURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.PublicKeyURL");
	}

	/**
	* Use the scheme from deep link configuration used in the "build native mobile app"
	*/
	public static java.lang.String getScheme()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.Scheme");
	}

	public static java.lang.String getSiemensInsightsHubSingleSignOn_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.SiemensInsightsHubSingleSignOn_Version");
	}

	/**
	* Value is used for local development. Defaults to "max.musterman@email.com" in case no value provided.
	* 
	* Will be set as email of the current "Account".
	* 
	* 
	*/
	public static java.lang.String getUserEmail()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.UserEmail");
	}

	/**
	* Name of the user tenant.
	* Name is used during retrieval of application credentials.
	*/
	public static java.lang.String getUserTenant()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubSingleSignOn.UserTenant");
	}
}