// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubsinglesignon.proxies;

public class AccessToken
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accessTokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SiemensInsightsHubSingleSignOn.AccessToken";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Access_token("Access_token"),
		Tenant("Tenant"),
		ShowToken("ShowToken");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AccessToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AccessToken(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accessTokenMendixObject)
	{
		if (accessTokenMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, accessTokenMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.accessTokenMendixObject = accessTokenMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AccessToken.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static siemensinsightshubsinglesignon.proxies.AccessToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return siemensinsightshubsinglesignon.proxies.AccessToken.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static siemensinsightshubsinglesignon.proxies.AccessToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new siemensinsightshubsinglesignon.proxies.AccessToken(context, mendixObject);
	}

	public static siemensinsightshubsinglesignon.proxies.AccessToken load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return siemensinsightshubsinglesignon.proxies.AccessToken.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of Tenant
	 */
	public final java.lang.String getTenant()
	{
		return getTenant(getContext());
	}

	/**
	 * @param context
	 * @return value of Tenant
	 */
	public final java.lang.String getTenant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Tenant.toString());
	}

	/**
	 * Set value of Tenant
	 * @param tenant
	 */
	public final void setTenant(java.lang.String tenant)
	{
		setTenant(getContext(), tenant);
	}

	/**
	 * Set value of Tenant
	 * @param context
	 * @param tenant
	 */
	public final void setTenant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tenant)
	{
		getMendixObject().setValue(context, MemberNames.Tenant.toString(), tenant);
	}

	/**
	 * @return value of ShowToken
	 */
	public final java.lang.Boolean getShowToken()
	{
		return getShowToken(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowToken
	 */
	public final java.lang.Boolean getShowToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowToken.toString());
	}

	/**
	 * Set value of ShowToken
	 * @param showtoken
	 */
	public final void setShowToken(java.lang.Boolean showtoken)
	{
		setShowToken(getContext(), showtoken);
	}

	/**
	 * Set value of ShowToken
	 * @param context
	 * @param showtoken
	 */
	public final void setShowToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showtoken)
	{
		getMendixObject().setValue(context, MemberNames.ShowToken.toString(), showtoken);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accessTokenMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final siemensinsightshubsinglesignon.proxies.AccessToken that = (siemensinsightshubsinglesignon.proxies.AccessToken) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
