// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubsinglesignon.proxies;

public class CredentialsResponse
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject credentialsResponseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SiemensInsightsHubSingleSignOn.CredentialsResponse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Access_token("Access_token"),
		Token_type("Token_type"),
		Expires_in("Expires_in"),
		Scope("Scope"),
		Expires_at("Expires_at"),
		Jit("Jit"),
		StatusCode("StatusCode"),
		ErrorType("ErrorType"),
		ErrorMessage("ErrorMessage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CredentialsResponse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CredentialsResponse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject credentialsResponseMendixObject)
	{
		if (credentialsResponseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, credentialsResponseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.credentialsResponseMendixObject = credentialsResponseMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CredentialsResponse.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static siemensinsightshubsinglesignon.proxies.CredentialsResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return siemensinsightshubsinglesignon.proxies.CredentialsResponse.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static siemensinsightshubsinglesignon.proxies.CredentialsResponse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new siemensinsightshubsinglesignon.proxies.CredentialsResponse(context, mendixObject);
	}

	public static siemensinsightshubsinglesignon.proxies.CredentialsResponse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return siemensinsightshubsinglesignon.proxies.CredentialsResponse.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token()
	{
		return getAccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of Access_token
	 */
	public final java.lang.String getAccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Access_token.toString());
	}

	/**
	 * Set value of Access_token
	 * @param access_token
	 */
	public final void setAccess_token(java.lang.String access_token)
	{
		setAccess_token(getContext(), access_token);
	}

	/**
	 * Set value of Access_token
	 * @param context
	 * @param access_token
	 */
	public final void setAccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.Access_token.toString(), access_token);
	}

	/**
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type()
	{
		return getToken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of Token_type
	 */
	public final java.lang.String getToken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Token_type.toString());
	}

	/**
	 * Set value of Token_type
	 * @param token_type
	 */
	public final void setToken_type(java.lang.String token_type)
	{
		setToken_type(getContext(), token_type);
	}

	/**
	 * Set value of Token_type
	 * @param context
	 * @param token_type
	 */
	public final void setToken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.Token_type.toString(), token_type);
	}

	/**
	 * @return value of Expires_in
	 */
	public final java.lang.Integer getExpires_in()
	{
		return getExpires_in(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_in
	 */
	public final java.lang.Integer getExpires_in(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Expires_in.toString());
	}

	/**
	 * Set value of Expires_in
	 * @param expires_in
	 */
	public final void setExpires_in(java.lang.Integer expires_in)
	{
		setExpires_in(getContext(), expires_in);
	}

	/**
	 * Set value of Expires_in
	 * @param context
	 * @param expires_in
	 */
	public final void setExpires_in(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expires_in)
	{
		getMendixObject().setValue(context, MemberNames.Expires_in.toString(), expires_in);
	}

	/**
	 * @return value of Scope
	 */
	public final java.lang.String getScope()
	{
		return getScope(getContext());
	}

	/**
	 * @param context
	 * @return value of Scope
	 */
	public final java.lang.String getScope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Scope.toString());
	}

	/**
	 * Set value of Scope
	 * @param scope
	 */
	public final void setScope(java.lang.String scope)
	{
		setScope(getContext(), scope);
	}

	/**
	 * Set value of Scope
	 * @param context
	 * @param scope
	 */
	public final void setScope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.Scope.toString(), scope);
	}

	/**
	 * @return value of Expires_at
	 */
	public final java.util.Date getExpires_at()
	{
		return getExpires_at(getContext());
	}

	/**
	 * @param context
	 * @return value of Expires_at
	 */
	public final java.util.Date getExpires_at(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Expires_at.toString());
	}

	/**
	 * Set value of Expires_at
	 * @param expires_at
	 */
	public final void setExpires_at(java.util.Date expires_at)
	{
		setExpires_at(getContext(), expires_at);
	}

	/**
	 * Set value of Expires_at
	 * @param context
	 * @param expires_at
	 */
	public final void setExpires_at(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date expires_at)
	{
		getMendixObject().setValue(context, MemberNames.Expires_at.toString(), expires_at);
	}

	/**
	 * @return value of Jit
	 */
	public final java.lang.String getJit()
	{
		return getJit(getContext());
	}

	/**
	 * @param context
	 * @return value of Jit
	 */
	public final java.lang.String getJit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Jit.toString());
	}

	/**
	 * Set value of Jit
	 * @param jit
	 */
	public final void setJit(java.lang.String jit)
	{
		setJit(getContext(), jit);
	}

	/**
	 * Set value of Jit
	 * @param context
	 * @param jit
	 */
	public final void setJit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jit)
	{
		getMendixObject().setValue(context, MemberNames.Jit.toString(), jit);
	}

	/**
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode()
	{
		return getStatusCode(getContext());
	}

	/**
	 * @param context
	 * @return value of StatusCode
	 */
	public final java.lang.Integer getStatusCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StatusCode.toString());
	}

	/**
	 * Set value of StatusCode
	 * @param statuscode
	 */
	public final void setStatusCode(java.lang.Integer statuscode)
	{
		setStatusCode(getContext(), statuscode);
	}

	/**
	 * Set value of StatusCode
	 * @param context
	 * @param statuscode
	 */
	public final void setStatusCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer statuscode)
	{
		getMendixObject().setValue(context, MemberNames.StatusCode.toString(), statuscode);
	}

	/**
	 * @return value of ErrorType
	 */
	public final java.lang.String getErrorType()
	{
		return getErrorType(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorType
	 */
	public final java.lang.String getErrorType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorType.toString());
	}

	/**
	 * Set value of ErrorType
	 * @param errortype
	 */
	public final void setErrorType(java.lang.String errortype)
	{
		setErrorType(getContext(), errortype);
	}

	/**
	 * Set value of ErrorType
	 * @param context
	 * @param errortype
	 */
	public final void setErrorType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errortype)
	{
		getMendixObject().setValue(context, MemberNames.ErrorType.toString(), errortype);
	}

	/**
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage()
	{
		return getErrorMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of ErrorMessage
	 */
	public final java.lang.String getErrorMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ErrorMessage.toString());
	}

	/**
	 * Set value of ErrorMessage
	 * @param errormessage
	 */
	public final void setErrorMessage(java.lang.String errormessage)
	{
		setErrorMessage(getContext(), errormessage);
	}

	/**
	 * Set value of ErrorMessage
	 * @param context
	 * @param errormessage
	 */
	public final void setErrorMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String errormessage)
	{
		getMendixObject().setValue(context, MemberNames.ErrorMessage.toString(), errormessage);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return credentialsResponseMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final siemensinsightshubsinglesignon.proxies.CredentialsResponse that = (siemensinsightshubsinglesignon.proxies.CredentialsResponse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
