// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubsinglesignon.proxies;

/**
 * Used to provide Cloud Foundry Environment Variables to the app.
 * Object is created and filled from a Java - action which handles the cases running on CF or locally.
 * When running on a Developer Tenant the user must create the 5 attributes as env-variables. On a Operator Tenant these Variables are provided by InsightsHub.
 */
public class MDSP_ENV
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mDSP_ENVMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SiemensInsightsHubSingleSignOn.MDSP_ENV";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MDSP_KEY_STORE_CLIENT_ID("MDSP_KEY_STORE_CLIENT_ID"),
		MDSP_KEY_STORE_CLIENT_SECRET("MDSP_KEY_STORE_CLIENT_SECRET"),
		MDSP_OS_VM_APP_NAME("MDSP_OS_VM_APP_NAME"),
		MDSP_OS_VM_APP_VERSION("MDSP_OS_VM_APP_VERSION"),
		MDSP_OS_VM_HOST_TENANT("MDSP_OS_VM_HOST_TENANT");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MDSP_ENV(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MDSP_ENV(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mDSP_ENVMendixObject)
	{
		if (mDSP_ENVMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, mDSP_ENVMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mDSP_ENVMendixObject = mDSP_ENVMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MDSP_ENV.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static siemensinsightshubsinglesignon.proxies.MDSP_ENV initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return siemensinsightshubsinglesignon.proxies.MDSP_ENV.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static siemensinsightshubsinglesignon.proxies.MDSP_ENV initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new siemensinsightshubsinglesignon.proxies.MDSP_ENV(context, mendixObject);
	}

	public static siemensinsightshubsinglesignon.proxies.MDSP_ENV load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return siemensinsightshubsinglesignon.proxies.MDSP_ENV.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MDSP_KEY_STORE_CLIENT_ID
	 */
	public final java.lang.String getMDSP_KEY_STORE_CLIENT_ID()
	{
		return getMDSP_KEY_STORE_CLIENT_ID(getContext());
	}

	/**
	 * @param context
	 * @return value of MDSP_KEY_STORE_CLIENT_ID
	 */
	public final java.lang.String getMDSP_KEY_STORE_CLIENT_ID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MDSP_KEY_STORE_CLIENT_ID.toString());
	}

	/**
	 * Set value of MDSP_KEY_STORE_CLIENT_ID
	 * @param mdsp_key_store_client_id
	 */
	public final void setMDSP_KEY_STORE_CLIENT_ID(java.lang.String mdsp_key_store_client_id)
	{
		setMDSP_KEY_STORE_CLIENT_ID(getContext(), mdsp_key_store_client_id);
	}

	/**
	 * Set value of MDSP_KEY_STORE_CLIENT_ID
	 * @param context
	 * @param mdsp_key_store_client_id
	 */
	public final void setMDSP_KEY_STORE_CLIENT_ID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mdsp_key_store_client_id)
	{
		getMendixObject().setValue(context, MemberNames.MDSP_KEY_STORE_CLIENT_ID.toString(), mdsp_key_store_client_id);
	}

	/**
	 * @return value of MDSP_KEY_STORE_CLIENT_SECRET
	 */
	public final java.lang.String getMDSP_KEY_STORE_CLIENT_SECRET()
	{
		return getMDSP_KEY_STORE_CLIENT_SECRET(getContext());
	}

	/**
	 * @param context
	 * @return value of MDSP_KEY_STORE_CLIENT_SECRET
	 */
	public final java.lang.String getMDSP_KEY_STORE_CLIENT_SECRET(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MDSP_KEY_STORE_CLIENT_SECRET.toString());
	}

	/**
	 * Set value of MDSP_KEY_STORE_CLIENT_SECRET
	 * @param mdsp_key_store_client_secret
	 */
	public final void setMDSP_KEY_STORE_CLIENT_SECRET(java.lang.String mdsp_key_store_client_secret)
	{
		setMDSP_KEY_STORE_CLIENT_SECRET(getContext(), mdsp_key_store_client_secret);
	}

	/**
	 * Set value of MDSP_KEY_STORE_CLIENT_SECRET
	 * @param context
	 * @param mdsp_key_store_client_secret
	 */
	public final void setMDSP_KEY_STORE_CLIENT_SECRET(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mdsp_key_store_client_secret)
	{
		getMendixObject().setValue(context, MemberNames.MDSP_KEY_STORE_CLIENT_SECRET.toString(), mdsp_key_store_client_secret);
	}

	/**
	 * @return value of MDSP_OS_VM_APP_NAME
	 */
	public final java.lang.String getMDSP_OS_VM_APP_NAME()
	{
		return getMDSP_OS_VM_APP_NAME(getContext());
	}

	/**
	 * @param context
	 * @return value of MDSP_OS_VM_APP_NAME
	 */
	public final java.lang.String getMDSP_OS_VM_APP_NAME(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MDSP_OS_VM_APP_NAME.toString());
	}

	/**
	 * Set value of MDSP_OS_VM_APP_NAME
	 * @param mdsp_os_vm_app_name
	 */
	public final void setMDSP_OS_VM_APP_NAME(java.lang.String mdsp_os_vm_app_name)
	{
		setMDSP_OS_VM_APP_NAME(getContext(), mdsp_os_vm_app_name);
	}

	/**
	 * Set value of MDSP_OS_VM_APP_NAME
	 * @param context
	 * @param mdsp_os_vm_app_name
	 */
	public final void setMDSP_OS_VM_APP_NAME(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mdsp_os_vm_app_name)
	{
		getMendixObject().setValue(context, MemberNames.MDSP_OS_VM_APP_NAME.toString(), mdsp_os_vm_app_name);
	}

	/**
	 * @return value of MDSP_OS_VM_APP_VERSION
	 */
	public final java.lang.String getMDSP_OS_VM_APP_VERSION()
	{
		return getMDSP_OS_VM_APP_VERSION(getContext());
	}

	/**
	 * @param context
	 * @return value of MDSP_OS_VM_APP_VERSION
	 */
	public final java.lang.String getMDSP_OS_VM_APP_VERSION(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MDSP_OS_VM_APP_VERSION.toString());
	}

	/**
	 * Set value of MDSP_OS_VM_APP_VERSION
	 * @param mdsp_os_vm_app_version
	 */
	public final void setMDSP_OS_VM_APP_VERSION(java.lang.String mdsp_os_vm_app_version)
	{
		setMDSP_OS_VM_APP_VERSION(getContext(), mdsp_os_vm_app_version);
	}

	/**
	 * Set value of MDSP_OS_VM_APP_VERSION
	 * @param context
	 * @param mdsp_os_vm_app_version
	 */
	public final void setMDSP_OS_VM_APP_VERSION(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mdsp_os_vm_app_version)
	{
		getMendixObject().setValue(context, MemberNames.MDSP_OS_VM_APP_VERSION.toString(), mdsp_os_vm_app_version);
	}

	/**
	 * @return value of MDSP_OS_VM_HOST_TENANT
	 */
	public final java.lang.String getMDSP_OS_VM_HOST_TENANT()
	{
		return getMDSP_OS_VM_HOST_TENANT(getContext());
	}

	/**
	 * @param context
	 * @return value of MDSP_OS_VM_HOST_TENANT
	 */
	public final java.lang.String getMDSP_OS_VM_HOST_TENANT(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MDSP_OS_VM_HOST_TENANT.toString());
	}

	/**
	 * Set value of MDSP_OS_VM_HOST_TENANT
	 * @param mdsp_os_vm_host_tenant
	 */
	public final void setMDSP_OS_VM_HOST_TENANT(java.lang.String mdsp_os_vm_host_tenant)
	{
		setMDSP_OS_VM_HOST_TENANT(getContext(), mdsp_os_vm_host_tenant);
	}

	/**
	 * Set value of MDSP_OS_VM_HOST_TENANT
	 * @param context
	 * @param mdsp_os_vm_host_tenant
	 */
	public final void setMDSP_OS_VM_HOST_TENANT(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mdsp_os_vm_host_tenant)
	{
		getMendixObject().setValue(context, MemberNames.MDSP_OS_VM_HOST_TENANT.toString(), mdsp_os_vm_host_tenant);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mDSP_ENVMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final siemensinsightshubsinglesignon.proxies.MDSP_ENV that = (siemensinsightshubsinglesignon.proxies.MDSP_ENV) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
