// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubsinglesignon.proxies;

public class MobileToken
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mobileTokenMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SiemensInsightsHubSingleSignOn.MobileToken";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		access_token("access_token"),
		token_type("token_type"),
		refresh_token("refresh_token"),
		expires_in("expires_in"),
		scope("scope"),
		jti("jti"),
		access_token_expires_at("access_token_expires_at"),
		refresh_token_expires_at("refresh_token_expires_at"),
		error("error"),
		SecretLoginToken("SecretLoginToken"),
		message("message"),
		tenant_name("tenant_name");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MobileToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MobileToken(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mobileTokenMendixObject)
	{
		if (mobileTokenMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, mobileTokenMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mobileTokenMendixObject = mobileTokenMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MobileToken.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static siemensinsightshubsinglesignon.proxies.MobileToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return siemensinsightshubsinglesignon.proxies.MobileToken.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static siemensinsightshubsinglesignon.proxies.MobileToken initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new siemensinsightshubsinglesignon.proxies.MobileToken(context, mendixObject);
	}

	public static siemensinsightshubsinglesignon.proxies.MobileToken load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return siemensinsightshubsinglesignon.proxies.MobileToken.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of access_token
	 */
	public final java.lang.String getaccess_token()
	{
		return getaccess_token(getContext());
	}

	/**
	 * @param context
	 * @return value of access_token
	 */
	public final java.lang.String getaccess_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.access_token.toString());
	}

	/**
	 * Set value of access_token
	 * @param access_token
	 */
	public final void setaccess_token(java.lang.String access_token)
	{
		setaccess_token(getContext(), access_token);
	}

	/**
	 * Set value of access_token
	 * @param context
	 * @param access_token
	 */
	public final void setaccess_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String access_token)
	{
		getMendixObject().setValue(context, MemberNames.access_token.toString(), access_token);
	}

	/**
	 * @return value of token_type
	 */
	public final java.lang.String gettoken_type()
	{
		return gettoken_type(getContext());
	}

	/**
	 * @param context
	 * @return value of token_type
	 */
	public final java.lang.String gettoken_type(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.token_type.toString());
	}

	/**
	 * Set value of token_type
	 * @param token_type
	 */
	public final void settoken_type(java.lang.String token_type)
	{
		settoken_type(getContext(), token_type);
	}

	/**
	 * Set value of token_type
	 * @param context
	 * @param token_type
	 */
	public final void settoken_type(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String token_type)
	{
		getMendixObject().setValue(context, MemberNames.token_type.toString(), token_type);
	}

	/**
	 * @return value of refresh_token
	 */
	public final java.lang.String getrefresh_token()
	{
		return getrefresh_token(getContext());
	}

	/**
	 * @param context
	 * @return value of refresh_token
	 */
	public final java.lang.String getrefresh_token(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.refresh_token.toString());
	}

	/**
	 * Set value of refresh_token
	 * @param refresh_token
	 */
	public final void setrefresh_token(java.lang.String refresh_token)
	{
		setrefresh_token(getContext(), refresh_token);
	}

	/**
	 * Set value of refresh_token
	 * @param context
	 * @param refresh_token
	 */
	public final void setrefresh_token(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String refresh_token)
	{
		getMendixObject().setValue(context, MemberNames.refresh_token.toString(), refresh_token);
	}

	/**
	 * @return value of expires_in
	 */
	public final java.lang.Integer getexpires_in()
	{
		return getexpires_in(getContext());
	}

	/**
	 * @param context
	 * @return value of expires_in
	 */
	public final java.lang.Integer getexpires_in(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.expires_in.toString());
	}

	/**
	 * Set value of expires_in
	 * @param expires_in
	 */
	public final void setexpires_in(java.lang.Integer expires_in)
	{
		setexpires_in(getContext(), expires_in);
	}

	/**
	 * Set value of expires_in
	 * @param context
	 * @param expires_in
	 */
	public final void setexpires_in(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer expires_in)
	{
		getMendixObject().setValue(context, MemberNames.expires_in.toString(), expires_in);
	}

	/**
	 * @return value of scope
	 */
	public final java.lang.String getscope()
	{
		return getscope(getContext());
	}

	/**
	 * @param context
	 * @return value of scope
	 */
	public final java.lang.String getscope(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.scope.toString());
	}

	/**
	 * Set value of scope
	 * @param scope
	 */
	public final void setscope(java.lang.String scope)
	{
		setscope(getContext(), scope);
	}

	/**
	 * Set value of scope
	 * @param context
	 * @param scope
	 */
	public final void setscope(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String scope)
	{
		getMendixObject().setValue(context, MemberNames.scope.toString(), scope);
	}

	/**
	 * @return value of jti
	 */
	public final java.lang.String getjti()
	{
		return getjti(getContext());
	}

	/**
	 * @param context
	 * @return value of jti
	 */
	public final java.lang.String getjti(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.jti.toString());
	}

	/**
	 * Set value of jti
	 * @param jti
	 */
	public final void setjti(java.lang.String jti)
	{
		setjti(getContext(), jti);
	}

	/**
	 * Set value of jti
	 * @param context
	 * @param jti
	 */
	public final void setjti(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jti)
	{
		getMendixObject().setValue(context, MemberNames.jti.toString(), jti);
	}

	/**
	 * @return value of access_token_expires_at
	 */
	public final java.util.Date getaccess_token_expires_at()
	{
		return getaccess_token_expires_at(getContext());
	}

	/**
	 * @param context
	 * @return value of access_token_expires_at
	 */
	public final java.util.Date getaccess_token_expires_at(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.access_token_expires_at.toString());
	}

	/**
	 * Set value of access_token_expires_at
	 * @param access_token_expires_at
	 */
	public final void setaccess_token_expires_at(java.util.Date access_token_expires_at)
	{
		setaccess_token_expires_at(getContext(), access_token_expires_at);
	}

	/**
	 * Set value of access_token_expires_at
	 * @param context
	 * @param access_token_expires_at
	 */
	public final void setaccess_token_expires_at(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date access_token_expires_at)
	{
		getMendixObject().setValue(context, MemberNames.access_token_expires_at.toString(), access_token_expires_at);
	}

	/**
	 * @return value of refresh_token_expires_at
	 */
	public final java.util.Date getrefresh_token_expires_at()
	{
		return getrefresh_token_expires_at(getContext());
	}

	/**
	 * @param context
	 * @return value of refresh_token_expires_at
	 */
	public final java.util.Date getrefresh_token_expires_at(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.refresh_token_expires_at.toString());
	}

	/**
	 * Set value of refresh_token_expires_at
	 * @param refresh_token_expires_at
	 */
	public final void setrefresh_token_expires_at(java.util.Date refresh_token_expires_at)
	{
		setrefresh_token_expires_at(getContext(), refresh_token_expires_at);
	}

	/**
	 * Set value of refresh_token_expires_at
	 * @param context
	 * @param refresh_token_expires_at
	 */
	public final void setrefresh_token_expires_at(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date refresh_token_expires_at)
	{
		getMendixObject().setValue(context, MemberNames.refresh_token_expires_at.toString(), refresh_token_expires_at);
	}

	/**
	 * @return value of error
	 */
	public final java.lang.Boolean geterror()
	{
		return geterror(getContext());
	}

	/**
	 * @param context
	 * @return value of error
	 */
	public final java.lang.Boolean geterror(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.error.toString());
	}

	/**
	 * Set value of error
	 * @param error
	 */
	public final void seterror(java.lang.Boolean error)
	{
		seterror(getContext(), error);
	}

	/**
	 * Set value of error
	 * @param context
	 * @param error
	 */
	public final void seterror(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean error)
	{
		getMendixObject().setValue(context, MemberNames.error.toString(), error);
	}

	/**
	 * @return value of SecretLoginToken
	 */
	public final java.lang.String getSecretLoginToken()
	{
		return getSecretLoginToken(getContext());
	}

	/**
	 * @param context
	 * @return value of SecretLoginToken
	 */
	public final java.lang.String getSecretLoginToken(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SecretLoginToken.toString());
	}

	/**
	 * Set value of SecretLoginToken
	 * @param secretlogintoken
	 */
	public final void setSecretLoginToken(java.lang.String secretlogintoken)
	{
		setSecretLoginToken(getContext(), secretlogintoken);
	}

	/**
	 * Set value of SecretLoginToken
	 * @param context
	 * @param secretlogintoken
	 */
	public final void setSecretLoginToken(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String secretlogintoken)
	{
		getMendixObject().setValue(context, MemberNames.SecretLoginToken.toString(), secretlogintoken);
	}

	/**
	 * @return value of message
	 */
	public final java.lang.String getmessage()
	{
		return getmessage(getContext());
	}

	/**
	 * @param context
	 * @return value of message
	 */
	public final java.lang.String getmessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.message.toString());
	}

	/**
	 * Set value of message
	 * @param message
	 */
	public final void setmessage(java.lang.String message)
	{
		setmessage(getContext(), message);
	}

	/**
	 * Set value of message
	 * @param context
	 * @param message
	 */
	public final void setmessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.message.toString(), message);
	}

	/**
	 * @return value of tenant_name
	 */
	public final java.lang.String gettenant_name()
	{
		return gettenant_name(getContext());
	}

	/**
	 * @param context
	 * @return value of tenant_name
	 */
	public final java.lang.String gettenant_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.tenant_name.toString());
	}

	/**
	 * Set value of tenant_name
	 * @param tenant_name
	 */
	public final void settenant_name(java.lang.String tenant_name)
	{
		settenant_name(getContext(), tenant_name);
	}

	/**
	 * Set value of tenant_name
	 * @param context
	 * @param tenant_name
	 */
	public final void settenant_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tenant_name)
	{
		getMendixObject().setValue(context, MemberNames.tenant_name.toString(), tenant_name);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mobileTokenMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final siemensinsightshubsinglesignon.proxies.MobileToken that = (siemensinsightshubsinglesignon.proxies.MobileToken) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
