// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubsinglesignon.proxies;

public class TenantObject
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tenantObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "SiemensInsightsHubSingleSignOn.TenantObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TenantObject_Tenant("SiemensInsightsHubSingleSignOn.TenantObject_Tenant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TenantObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TenantObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tenantObjectMendixObject)
	{
		if (tenantObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, tenantObjectMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tenantObjectMendixObject = tenantObjectMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TenantObject.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static siemensinsightshubsinglesignon.proxies.TenantObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return siemensinsightshubsinglesignon.proxies.TenantObject.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static siemensinsightshubsinglesignon.proxies.TenantObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("SiemensInsightsHubSingleSignOn.TokenForScheduledEvents", mendixObject.getType())) {
			return siemensinsightshubsinglesignon.proxies.TokenForScheduledEvents.initialize(context, mendixObject);
		}
		return new siemensinsightshubsinglesignon.proxies.TenantObject(context, mendixObject);
	}

	public static siemensinsightshubsinglesignon.proxies.TenantObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return siemensinsightshubsinglesignon.proxies.TenantObject.initialize(context, mendixObject);
	}

	public static java.util.List<? extends siemensinsightshubsinglesignon.proxies.TenantObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> siemensinsightshubsinglesignon.proxies.TenantObject.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TenantObject_Tenant
	 */
	public final siemensinsightshubsinglesignon.proxies.Tenant getTenantObject_Tenant() throws com.mendix.core.CoreException
	{
		return getTenantObject_Tenant(getContext());
	}

	/**
	 * @param context
	 * @return value of TenantObject_Tenant
	 * @throws com.mendix.core.CoreException
	 */
	public final siemensinsightshubsinglesignon.proxies.Tenant getTenantObject_Tenant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		siemensinsightshubsinglesignon.proxies.Tenant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TenantObject_Tenant.toString());
		if (identifier != null) {
			result = siemensinsightshubsinglesignon.proxies.Tenant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TenantObject_Tenant
	 * @param tenantobject_tenant
	 */
	public final void setTenantObject_Tenant(siemensinsightshubsinglesignon.proxies.Tenant tenantobject_tenant)
	{
		setTenantObject_Tenant(getContext(), tenantobject_tenant);
	}

	/**
	 * Set value of TenantObject_Tenant
	 * @param context
	 * @param tenantobject_tenant
	 */
	public final void setTenantObject_Tenant(com.mendix.systemwideinterfaces.core.IContext context, siemensinsightshubsinglesignon.proxies.Tenant tenantobject_tenant)
	{
		if (tenantobject_tenant == null) {
			getMendixObject().setValue(context, MemberNames.TenantObject_Tenant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TenantObject_Tenant.toString(), tenantobject_tenant.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tenantObjectMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final siemensinsightshubsinglesignon.proxies.TenantObject that = (siemensinsightshubsinglesignon.proxies.TenantObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
