// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import UrlParse from "url-parse";

// BEGIN EXTRA CODE
async function getURLPath(url){
	const urlObject = new UrlParse(url);
	return urlObject.pathname;
}
// END EXTRA CODE

/**
 * @param {string} uRL
 * @returns {Promise.<string>}
 */
export async function URLPath(uRL) {
	// BEGIN USER CODE
	return getURLPath(uRL);
	// END USER CODE
}
