// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package siemensinsightshubsinglesignon.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import siemensinsightshubsinglesignon.CheckAuthentication;
import siemensinsightshubsinglesignon.proxies.constants.Constants;

public class AuthenticateRestAPI extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Response;
	private system.proxies.HttpResponse Response;
	private java.lang.String Authorization;

	public AuthenticateRestAPI(IContext context, IMendixObject Response, java.lang.String Authorization)
	{
		super(context);
		this.__Response = Response;
		this.Authorization = Authorization;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Response = this.__Response == null ? null : system.proxies.HttpResponse.initialize(getContext(), __Response);

		// BEGIN USER CODE
		LOGGER.debug("Start Authenticate REST API");
		CheckAuthentication checkAuthentication = new CheckAuthentication(this.context(), Response, Authorization);
		IMendixObject user = checkAuthentication.check();		
		LOGGER.debug("Finish Authenticate Rest API");
		return user;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AuthenticateRestAPI";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode LOGGER = Core.getLogger(Constants.getModuleName());
	// END EXTRA CODE
}
