// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package siemensinsightshubsinglesignon.actions;

import java.util.Base64;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CalcBase64Credentials extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __CredentialsParameter1;
	private siemensinsightshubsinglesignon.proxies.Credentials CredentialsParameter1;

	public CalcBase64Credentials(IContext context, IMendixObject CredentialsParameter1)
	{
		super(context);
		this.__CredentialsParameter1 = CredentialsParameter1;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.CredentialsParameter1 = this.__CredentialsParameter1 == null ? null : siemensinsightshubsinglesignon.proxies.Credentials.initialize(getContext(), __CredentialsParameter1);

		// BEGIN USER CODE
		// set the Base64Credentials for the given clientId and clientSecret credentials case
		CredentialsParameter1.setBase64Credentials("Basic " + Base64.getEncoder().encodeToString(
				(CredentialsParameter1.getClientID() + ":" + CredentialsParameter1.getClientSecret())
						.getBytes()));
		
		return CredentialsParameter1.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CalcBase64Credentials";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
