// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package siemensinsightshubsinglesignon.actions;

import java.util.Optional;
import inh_org.jose4j.jwt.JwtClaims;
import inh_org.jose4j.jwt.MalformedClaimException;
import inh_org.jose4j.jwt.consumer.InvalidJwtException;
import inh_org.jose4j.jwt.consumer.JwtConsumer;
import inh_org.jose4j.jwt.consumer.JwtConsumerBuilder;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.m2ee.api.IMxRuntimeRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import siemensinsightshubsinglesignon.CredentialsHandler;
import siemensinsightshubsinglesignon.proxies.CredentialsResponse;
import siemensinsightshubsinglesignon.proxies.AccessToken;
import siemensinsightshubsinglesignon.proxies.constants.Constants;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetAccessToken extends CustomJavaAction<IMendixObject>
{
	public GetAccessToken(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		AccessToken accessToken = new AccessToken(context());
		getAccessTokenFromAuthHeader(accessToken);
		if (accessToken.getAccess_token() == null && System.getenv("VCAP_SERVICES") == null) {
			// Maybe there is a token via AppCredentials / ServiceCredentials stored in the current session.
			getAccessTokenFromCredentialsResponse(accessToken);
		}
		return accessToken.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetAccessToken";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode LOGGER = Core.getLogger(Constants.getModuleName());
	protected static JwtConsumer jwtConsumer = new JwtConsumerBuilder()				
			.setSkipAllDefaultValidators()
			.setSkipSignatureVerification()				
			.build();
	
	private void getAccessTokenFromAuthHeader(AccessToken accessToken) throws InvalidJwtException, MalformedClaimException {
		Optional<IMxRuntimeRequest> mayBeIMxRuntimeRequest = context().getRuntimeRequest();
		if (mayBeIMxRuntimeRequest.isPresent()) {
			String authHeader = mayBeIMxRuntimeRequest.get().getHeader("authorization");
			if (authHeader != null) {
				accessToken.setAccess_token(authHeader);
				addTenant(accessToken);
			}
		}
	}

	private void getAccessTokenFromCredentialsResponse(AccessToken accessToken) { //
		Optional<IMxRuntimeRequest> mayBeIMxRuntimeRequest = context().getRuntimeRequest();
		if (mayBeIMxRuntimeRequest.isPresent()) {
			CredentialsResponse ACResponse = CredentialsHandler.retrievCredentialsResponsFromSession(mayBeIMxRuntimeRequest.get()); 					
			if (ACResponse != null) {				
				accessToken.setAccess_token(ACResponse.getToken_type() + " " + ACResponse.getAccess_token());												
				addTenant(accessToken);
			}
		}
	}	
	
	private void addTenant(AccessToken accessToken) {				
		try {
			String jwt = accessToken.getAccess_token().replaceFirst("(?i)bearer ","");	
			JwtClaims claims = jwtConsumer.processToClaims(jwt);
			accessToken.setTenant(claims.getStringClaimValue("ten"));
		} catch (InvalidJwtException e) {
			LOGGER.error(e.getMessage());
		} catch (MalformedClaimException e) {
			LOGGER.error(e.getMessage());
		}		
	}
	// END EXTRA CODE
}
