// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package siemensinsightshubsinglesignon.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import siemensinsightshubsinglesignon.proxies.TokenForScheduledEvents;
import siemensinsightshubsinglesignon.proxies.microflows.Microflows;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ScheduledAccessTokenConnector extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Tenant;
	private siemensinsightshubsinglesignon.proxies.Tenant Tenant;

	public ScheduledAccessTokenConnector(IContext context, IMendixObject Tenant)
	{
		super(context);
		this.__Tenant = Tenant;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Tenant = this.__Tenant == null ? null : siemensinsightshubsinglesignon.proxies.Tenant.initialize(getContext(), __Tenant);

		// BEGIN USER CODE
		TokenForScheduledEvents accessToken = Microflows.dS_GetAccessTokenForScheduledEvents(context(), this.Tenant);
		
		if (accessToken == null) {
			return null;
		}		
		return accessToken.getMendixObject();
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ScheduledAccessTokenConnector";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
