// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubosbarconnector.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	/**
	 * @deprecated
	 * The default constructor of the Constants class should not be used.
	 * Use the static get methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Constants() {}

	// These are the constants for the SiemensInsightsHubOSBarConnector module

	public static java.lang.String getConfig()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubOSBarConnector.Config");
	}

	/**
	* URL of the Insights Hub OSBar.
	* For more details see here:
	* 
	* https://design.mindsphere.io/osbar/introduction.html#tab1anchor0
	*/
	public static java.lang.String getOSBarURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubOSBarConnector.OSBarURL");
	}

	public static java.lang.String getSiemensInsightsHubOSBarConnector_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("SiemensInsightsHubOSBarConnector.SiemensInsightsHubOSBarConnector_Version");
	}
}