// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package siemensinsightshubosbarconnector.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the SiemensInsightsHubOSBarConnector module
	public static java.lang.String pRS_GetConfig(IContext context, system.proxies.HttpResponse _httpResponse, boolean _all)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("HttpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		params.put("all", _all);
		return (java.lang.String) Core.microflowCall("SiemensInsightsHubOSBarConnector.PRS_GetConfig").withParams(params).execute(context);
	}
	public static system.proxies.HttpResponse pRS_LoadOSBar(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("SiemensInsightsHubOSBarConnector.PRS_LoadOSBar").withParams(params).execute(context);
		return result == null ? null : system.proxies.HttpResponse.initialize(context, result);
	}
	public static java.lang.String pRS_OSBarUrl(IContext context, system.proxies.HttpRequest _httpRequest, system.proxies.HttpResponse _httpResponse)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("httpRequest", _httpRequest == null ? null : _httpRequest.getMendixObject());
		params.put("httpResponse", _httpResponse == null ? null : _httpResponse.getMendixObject());
		return (java.lang.String) Core.microflowCall("SiemensInsightsHubOSBarConnector.PRS_OSBarUrl").withParams(params).execute(context);
	}
}
